name: ARM macOS Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    # 指定运行架构为 ARM64
    env:
      RUNNER_ARCH: arm64
    
    steps:
      - name: Check runner architecture
        run: |
          echo "Runner OS: $(uname -s)"
          echo "Runner Architecture: $(uname -m)"
          # 验证是否为 ARM 架构
          if [ "$(uname -m)" != "arm64" ]; then
            echo "Error: Not running on ARM architecture"
            exit 1
          fi
          
      - name: sakura frp
        run: |
          mkdir -p -m 755 /usr/local/bin && cd /usr/local/bin
          curl -Lo frpc https://nya.globalslb.net/natfrp/client/frpc/0.51.0-sakura-12.3/frpc_darwin_arm64
          chmod 755 frpc
          ls -ls frpc
          frpc -v
          frpc -f wadr25y8xv6h4ek361eoitlfsn7ow2nn:17573313 &

          
      - name: Enable Remote Desktop (ARM macOS)
        run: |
          # 启用远程管理（ARM 版本命令与 x86 相同）
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -on \
            -users admin -privs -all -restart -agent -menu
            
          # 其余配置与之前相同...
          sudo defaults write /var/db/launchd.db/com.apple.launchd/overrides.plist com.apple.screensharing -dict Disabled -bool false
          sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.screensharing.plist
          
      - name: Keep runner alive
        run: sleep 1800
