name: run docker

on:
  repository_dispatch:
    # types:
    #   - webhook

jobs:

  docker:
    name: run dockers
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - run: docker run -e TZ=Asia/Shanghai dlld0319/jobs:latest
