name: Build Lambda Package

on:
  workflow_dispatch:  # 允许手动触发
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: amazonlinux:2023
      
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          pip3.11 install -t ./build psycopg2-binary==2.9.9
          cp -r lambda_function/* ./build/
          
      - name: Create ZIP package
        run: |
          cd build && zip -r ../lambda_package.zip .
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda_package
          path: lambda_package.zip
