name: Install Ollama, Open-WebUI and Keep Running

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  run-ollama-webui:
    runs-on: ubuntu-latest
    timeout-minutes: 185  # 设置超时时间为185分钟（略多于3小时，预留缓冲时间）
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Ollama
      run: |
        curl -fsSL https://ollama.com/install.sh | sh
        
        # 启动Ollama服务并将其放入后台
        ollama serve &
        # 等待服务启动
        sleep 10
        
        # 验证安装并拉取示例模型
        ollama --version
        ollama pull llama3
        
    - name: Install and run Open-WebUI
      run: |
        # 确保Docker服务正在运行
        sudo systemctl start docker
        
        # 运行Open-WebUI容器
        docker run -d -p 3389:8080 \
          --add-host=host.docker.internal:host-gateway \
          -v open-webui:/app/backend/data \
          --name open-webui \
          --restart always \
          ghcr.io/open-webui/open-webui:main
        
        # 等待容器启动
        sleep 20
        
        # 检查容器运行状态
        docker ps | grep open-webui

        docker run \
        -d \
        --restart=always \
        --network=host \
        --pull=always \
        --name=sakura1 \
        natfrp.com/frpc \
        --disable_log_color \
         -f wadr25y8xv6h4ek361eoitlfsn7ow2nn:22904011
        
    - name: Keep running for 3 hours
      run: |
        echo "Starting 3-hour runtime period..."
        # 使用sleep命令保持进程活跃3小时（10800秒）
        sleep 10800
        echo "3-hour period completed"
