
on:
  workflow_dispatch:  # 允许手动触发
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: amazonlinux:2023
      
    steps:
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          run: |
            mkdir build
            pip install -t ./build psycopg2-binary==2.9.9
            ls
            cd build
            ls
            zip -r ../build.zip .
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build.zip
