name: run docker33
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          run: |
            pip install -t ./images psycopg2-binary==2.9.9
            cd images && zip -r ../images.zip .
            
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-deps
          path: images.zip
