on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: amazonlinux:2023
      
    steps:
      - name: Install system dependencies
        run: yum install -y zip python3.11

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build package
        run: |
          mkdir -p ./build
          pip install -t ./build psycopg2-binary==2.9.9
          cd build && zip -r ../build.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-deps
          path: ./build.zip
