name: run docker

on:
  workflow_dispatch

jobs:

  docker:
    name: run dockers
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: |
           docker build -t image_name .
           docker save image_name -o image_name.tar
           ls
           cd ..
           ls
           cd ..
           ls
      
      - name: Upload Docker image tar as artifact
        uses: actions/upload-artifact@v4
        with:
          name: image_name
          path: /images/
