name: VLESS Server with SakuraFrp

on:
  workflow_dispatch:
    inputs:
      port:
        description: 'VLESS 服务端监听端口'
        required: true
        default: '51012'
      uuid:
        description: 'VLESS UUID'
        required: true
        default: '2178250e-7cd3-404c-bcf4-02fe5f25d171'
      sakurafrp_token:
        description: 'SakuraFrp 认证令牌'
        required: true
        default: 'wadr25y8xv6h4ek361eoitlfsn7ow2nn'
      node_id:
        description: 'SakuraFrp 节点 ID'
        required: true
        default: '21663551'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up VLESS Server
        env:
          PORT: ${{ github.event.inputs.port }}
          UUID: ${{ github.event.inputs.uuid }}
          SAKURAFRP_TOKEN: ${{ github.event.inputs.sakurafrp_token }}
          NODE_ID: ${{ github.event.inputs.node_id }}
        run: |
          # 安装必要的软件
          sudo apt-get update
          sudo apt-get install -y wget unzip jq

          
          echo "下载 geosite.dat 和 geoip.dat..."
          wget -O /usr/local/share/xray/geosite.dat https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat
          wget -O /usr/local/share/xray/geoip.dat https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat
  
          # 下载并安装 Xray
          wget https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip
          unzip Xray-linux-64.zip -d xray
          sudo mv xray/xray /usr/local/bin/
          sudo chmod +x /usr/local/bin/xray

          # 创建 VLESS 服务端配置文件
          cat > config.json << EOF
            {
              "log": {
                "loglevel": "warning"
              },
              "dns": {
                "servers": [
                  "8.8.8.8",
                  "1.1.1.1",
                  {
                    "address": "114.114.114.114",
                    "port": 53,
                    "domains": [
                      "geosite:cn"
                    ]
                  },
                  "localhost"
                ],
                "queryStrategy": "UseIP",
                "disableCache": false,
                "enhancedMode": "fake-ip",
                "fakeIPRange": "198.18.0.1/16",
                "fakeIPFilter": [
                  "geoip:private",
                  "*.lan"
                ]
              },
              "inbounds": [
                {
                  "port": $PORT,
                  "protocol": "vless",
                  "settings": {
                    "clients": [
                      {
                        "id": "$UUID",
                        "level": 0
                      }
                    ],
                    "decryption": "none"
                  },
                  "streamSettings": {
                    "network": "tcp",
                    "security": "none"
                  }
                }
              ],
              "outbounds": [
                {
                  "protocol": "freedom",
                  "settings": {},
                  "tag": "proxy"
                },
                {
                  "protocol": "blackhole",
                  "settings": {
                    "response": {
                      "type": "http"
                    }
                  },
                  "tag": "block"
                },
                {
                  "protocol": "freedom",
                  "settings": {},
                  "tag": "direct"
                }
              ],
              "routing": {
                "domainStrategy": "IPOnDemand",
                "rules": [
                  {
                    "type": "field",
                    "domain": [
                      "geosite:category-ads-all"
                    ],
                    "outboundTag": "block"
                  },
                  {
                    "type": "field",
                    "domain": [
                      "geosite:google",
                      "geosite:twitter",
                      "geosite:facebook",
                      "geosite:telegram"
                    ],
                    "outboundTag": "proxy"
                  },
                  {
                    "type": "field",
                    "domain": [
                      "geosite:cn"
                    ],
                    "outboundTag": "direct"
                  },
                  {
                    "type": "field",
                    "ip": [
                      "geoip:private"
                    ],
                    "outboundTag": "direct"
                  },
                  {
                    "type": "field",
                    "ip": [
                      "geoip:cn"
                    ],
                    "outboundTag": "direct"
                  },
                  {
                    "type": "field",
                    "port": 53,
                    "outboundTag": "block"
                  },
                  {
                    "type": "field",
                    "network": "udp",
                    "outboundTag": "proxy"
                  }
                ]
              }
            }
          EOF
          
          # 调试：显示配置文件内容和大小
          echo "配置文件内容:"
          cat config.json
          echo "配置文件大小:"
          du -h config.json
          
          # 验证配置文件格式
          if ! jq . config.json >/dev/null 2>&1; then
            echo "配置文件格式错误!"
            exit 1
          fi

          # 启动 Xray（VLESS 服务端）
          sudo xray run -c config.json &
          sleep 5  # 等待 Xray 启动
         
          # 下载并配置 SakuraFrp 客户端
          docker run \
          -d \
          --restart=on-failure:5 \
          --network=host \
          --pull=always \
          --name=sakura1 \
          natfrp.com/frpc \
          --disable_log_color \
          -f wadr25y8xv6h4ek361eoitlfsn7ow2nn:21663551
          
          sleep 10  # 等待隧道启动
          
          # 输出服务信息
          echo "VLESS 服务端已通过 SakuraFrp 暴露"
          echo "公网域名: $SERVER_DOMAIN"
          echo "公网端口: $SERVER_PORT"
          echo "UUID: $UUID"
          
          # 生成新的 VLESS URL（使用 SakuraFrp 提供的域名和端口）
          VLESS_URL="vless://$UUID@$SERVER_DOMAIN:$SERVER_PORT?encryption=none&security=none&type=tcp#GitHub_Actions_VLESS"
          echo "VLESS URL: $VLESS_URL"
          
          # 保存配置信息
          cat > vless_config_info.txt << EOF
          VLESS 服务端配置信息:
          地址: $SERVER_DOMAIN
          端口: $SERVER_PORT
          用户ID: $UUID
          加密: none
          传输协议: tcp
          EOF
          docker logs sakura1
          # 保持服务运行
          while true; do sleep 3600; done
          
      - name: Upload server information
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: vless-server-info
          path: vless_config_info.txt
