name: VLESS Proxy Workflow

on:
  workflow_dispatch:
    inputs:
      port:
        description: '本地监听端口'
        required: true
        default: '1080'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up VLESS Proxy
        env:
          VLESS_CONFIG: ${{ secrets.VLESS_CONFIG }}
          PORT: ${{ github.event.inputs.port }}
        run: |
          # 安装必要的软件
          sudo apt-get update
          sudo apt-get install -y wget unzip

          # 下载并安装 Xray
          wget https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip
          unzip Xray-linux-64.zip -d xray
          sudo mv xray/xray /usr/local/bin/
          sudo chmod +x /usr/local/bin/xray

          # 创建 VLESS 配置文件
          echo "$VLESS_CONFIG" | base64 -d > config.json

          # 修改配置文件中的监听端口
          sed -i "s/1080/$PORT/g" config.json

          # 启动 Xray（VLESS 客户端）
          sudo xray run -c config.json &
          sleep 5  # 等待 Xray 启动

          # 验证代理是否工作
          curl -x socks5h://localhost:$PORT -s ifconfig.me
          
          # 输出访问信息
          PUBLIC_IP=$(curl -s ifconfig.me)
          echo "VLESS 代理已启动"
          echo "公网 IP: $PUBLIC_IP"
          echo "本地监听端口: $PORT"
          echo "代理地址: socks5://$PUBLIC_IP:$PORT"
          
          # 将访问信息保存到文件
          echo "代理地址: socks5://$PUBLIC_IP:$PORT" > vless_access_info.txt

          # 保持服务运行
          while true; do sleep 3600; done
          
      - name: Upload access information
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: vless-access-info
          path: vless_access_info.txt    
