name: VLESS Server Workflow

on:
  workflow_dispatch:
    inputs:
      port:
        description: 'VLESS 服务端监听端口'
        required: true
        default: '8080'
      uuid:
        description: 'VLESS UUID'
        required: true
        default: '2178250e-7cd3-404c-bcf4-02fe5f25d171'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up VLESS Server
        env:
          PORT: ${{ github.event.inputs.port }}
          UUID: ${{ github.event.inputs.uuid }}
        run: |
          # 安装必要的软件
          sudo apt-get update
          sudo apt-get install -y wget unzip jq

          # 下载并安装 Xray
          wget https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip
          unzip Xray-linux-64.zip -d xray
          sudo mv xray/xray /usr/local/bin/
          sudo chmod +x /usr/local/bin/xray

          # 创建 VLESS 服务端配置文件
          cat > config.json << EOF
          {
            "log": {
              "loglevel": "warning"
            },
            "inbounds": [
              {
                "port": $PORT,
                "protocol": "vless",
                "settings": {
                  "clients": [
                    {
                      "id": "\$UUID",
                      "level": 0
                    }
                  ],
                  "decryption": "none"
                },
                "streamSettings": {
                  "network": "tcp",
                  "security": "none"
                }
              }
            ],
            "outbounds": [
              {
                "protocol": "freedom",
                "settings": {}
              }
            ]
          }
          EOF
          
          # 调试：显示配置文件内容和大小
          echo "配置文件内容:"
          cat config.json
          echo "配置文件大小:"
          du -h config.json
          
          # 验证配置文件格式
          if ! jq . config.json >/dev/null 2>&1; then
            echo "配置文件格式错误!"
            exit 1
          fi

          # 开放端口
          sudo ufw allow $PORT/tcp

          # 启动 Xray（VLESS 服务端）
          sudo xray run -c config.json &
          sleep 5  # 等待 Xray 启动

          # 输出服务信息
          PUBLIC_IP=$(curl -s ifconfig.me)
          echo "VLESS 服务端已启动"
          echo "公网 IP: $PUBLIC_IP"
          echo "监听端口: $PORT"
          echo "UUID: $UUID"
          echo "配置信息:"
          echo "地址: $PUBLIC_IP"
          echo "端口: $PORT"
          echo "用户ID: $UUID"
          echo "加密: none"
          echo "传输协议: tcp"
          
          # 将访问信息保存到文件
          cat > vless_config_info.txt << EOF
          VLESS 服务端配置信息:
          地址: $PUBLIC_IP
          端口: $PORT
          用户ID: $UUID
          加密: none
          传输协议: tcp
          EOF

          # 保持服务运行
          while true; do sleep 3600; done
          
      - name: Upload server information
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: vless-server-info
          path: vless_config_info.txt
