name: Build and Package ffi-napi

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1
      
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      # - name: Configure node-gyp
      #   run: |
      #     npm config set msvs_version 2022
      #     npm config set node_gyp "C:\Users\runneradmin\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js"
      #   shell: powershell
      
      - name: Bypass windows-build-tools
        run: |
          # 创建一个空的windows-build-tools模块，避免安装
          mkdir -p node_modules/windows-build-tools
          echo "module.exports = { install: () => Promise.resolve() }" > node_modules/windows-build-tools/index.js
          
          # 安装ffi-napi，强制使用node-gyp编译
          npm install ffi-napi --build-from-source --ignore-scripts=false
        shell: powershell
      
      - name: Package ffi-napi as zip
        run: |
          Compress-Archive -Path node_modules\ffi-napi -DestinationPath ffi-napi-windows.zip
        shell: powershell
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffi-napi-windows
          path: ffi-napi-windows.zip
